# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY bridge_mcp_ghidra.py .

# Expose nothing (stdio by default), user can map ports for SSE

# Default entrypoint (overridden by MCP start command)
ENTRYPOINT ["python", "bridge_mcp_ghidra.py"]
