name: Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHIDRA_VERSION: 11.4.1
      GHIDRA_DATE: 20250731

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Download Ghidra
      run: |
        wget --no-verbose -O ghidra.zip https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${{ env.GHIDRA_VERSION }}_build/ghidra_${{ env.GHIDRA_VERSION }}_PUBLIC_${{ env.GHIDRA_DATE }}.zip
        7z x -bd ghidra.zip

    - name: Build with Gradle
      run: gradle

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GhidraMCP-artifact
        path: |
          release/*
